name = "nsnexus-prospeccao"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-01"

[vars]
FIREBASE_PROJECT_ID = "leeds-316cc"

[[d1_databases]]
binding = "DB"
database_name = "prospeccao-catalogo"
database_id = "c2a4e31c-7c77-4392-94aa-a91c9dbfd058"
migrations_dir = "migrations"
